import { useState, type FormEvent, type ReactNode } from "react";
import { Loader2, X } from "lucide-react";
import type { Member, Person, PlannedVisit, PrayerRequest } from "@/types";
import type { FollowUpInput, MeetingInput, MemberInput, PersonInput, PlannedVisitInput, PrayerRequestInput } from "@/lib/data";

type Kind="person"|"plannedVisit"|"prayer"|"followUp"|"meeting"|"member";
type Input=PersonInput|PlannedVisitInput|PrayerRequestInput|FollowUpInput|MeetingInput|MemberInput;
const field="w-full rounded-xl bg-[#f0f4f9] px-4 py-3 text-sm text-[#0d1b2e] outline-none focus:ring-2 focus:ring-[#0E5AA7]/20";
const F=({label,children}:{label:string;children:ReactNode})=><label className="block"><span className="mb-1.5 block text-xs font-black uppercase tracking-wide text-[#0d1b2e]">{label}</span>{children}</label>;
const local=(v?:string|null)=>v?new Date(v).toISOString().slice(0,16):"";
export function AdminCareDialog({kind,value,personId,onClose,onSave}:{kind:Kind;value?:Person|PlannedVisit|PrayerRequest|Member|null;personId?:string;onClose:()=>void;onSave:(input:Input)=>Promise<void>}){
 const[saving,setSaving]=useState(false),[error,setError]=useState("");
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setSaving(true);setError("");const d=new FormData(e.currentTarget),t=(n:string)=>String(d.get(n)||"")||null;let input:Input;
 if(kind==="person")input={firstName:String(d.get("firstName")),lastName:t("lastName"),email:t("email"),phone:t("phone"),address:t("address"),preferredContactMethod:String(d.get("preferredContactMethod")) as PersonInput["preferredContactMethod"],status:String(d.get("status")) as PersonInput["status"],source:t("source"),notes:t("notes")};
 else if(kind==="plannedVisit")input={name:String(d.get("name")),email:t("email"),phone:t("phone"),serviceName:String(d.get("serviceName")),visitDate:new Date(String(d.get("visitDate"))).toISOString(),source:t("source"),notes:t("notes")};
 else if(kind==="prayer")input={name:t("name"),email:t("email"),phone:t("phone"),isAnonymous:d.get("isAnonymous")==="on",requestText:String(d.get("requestText")),category:t("category"),urgency:String(d.get("urgency")) as PrayerRequestInput["urgency"]};
 else if(kind==="followUp")input={personId:personId!,type:String(d.get("type")) as FollowUpInput["type"],dueDate:t("dueDate")?new Date(String(d.get("dueDate"))).toISOString():null,notes:t("notes")};
 else if(kind==="meeting")input={personId:personId!,title:String(d.get("title")),startTime:new Date(String(d.get("startTime"))).toISOString(),endTime:t("endTime")?new Date(String(d.get("endTime"))).toISOString():null,location:t("location"),description:t("description")};
 else input={personId:personId!,membershipNumber:t("membershipNumber"),joinDate:t("joinDate")?new Date(String(d.get("joinDate"))).toISOString():undefined,role:t("role"),status:String(d.get("status")) as MemberInput["status"]};
 try{await onSave(input);onClose()}catch(err){setError(err instanceof Error?err.message:"Unable to save.")}finally{setSaving(false)}};
 const p=value as Person|undefined,pv=value as PlannedVisit|undefined,pr=value as PrayerRequest|undefined,m=value as Member|undefined;
 return <div className="fixed inset-0 z-[120] flex items-end justify-center bg-[#04183a]/60 sm:items-center sm:p-6"><form onSubmit={submit} className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-t-3xl bg-white p-6 shadow-2xl sm:rounded-3xl"><div className="mb-6 flex justify-between"><h2 className="text-xl font-black capitalize text-[#0d1b2e]">{kind.replace(/([A-Z])/g," $1")}</h2><button type="button" onClick={onClose}><X/></button></div><div className="space-y-4">
 {kind==="person"&&<><div className="grid gap-4 sm:grid-cols-2"><F label="First name"><input name="firstName" required className={field} defaultValue={p?.firstName}/></F><F label="Last name"><input name="lastName" className={field} defaultValue={p?.lastName??""}/></F><F label="Email"><input name="email" type="email" className={field} defaultValue={p?.email??""}/></F><F label="Phone"><input name="phone" className={field} defaultValue={p?.phone??""}/></F><F label="Address"><input name="address" className={field} defaultValue={p?.address??""}/></F><F label="Source"><input name="source" className={field} defaultValue={p?.source??""}/></F><F label="Contact preference"><select name="preferredContactMethod" className={field} defaultValue={p?.preferredContactMethod??"NONE"}>{["NONE","EMAIL","PHONE"].map(x=><option key={x}>{x}</option>)}</select></F><F label="Status"><select name="status" className={field} defaultValue={p?.status??"NEW"}>{["NEW","FOLLOW_UP","RETURNING","MEMBER","INACTIVE"].map(x=><option key={x}>{x}</option>)}</select></F></div><F label="Notes"><textarea name="notes" rows={3} className={field} defaultValue={p?.notes??""}/></F></>}
 {kind==="plannedVisit"&&<><div className="grid gap-4 sm:grid-cols-2"><F label="Name"><input name="name" required className={field} defaultValue={pv?.name}/></F><F label="Email"><input name="email" type="email" required className={field} defaultValue={pv?.email??""}/></F><F label="Phone"><input name="phone" className={field} defaultValue={pv?.phone??""}/></F><F label="Service"><input name="serviceName" required className={field} defaultValue={pv?.serviceName}/></F><F label="Visit date"><input name="visitDate" type="datetime-local" required className={field} defaultValue={local(pv?.visitDate)}/></F><F label="Source"><input name="source" className={field} defaultValue={pv?.source??""}/></F></div><F label="Notes"><textarea name="notes" rows={3} className={field} defaultValue={pv?.notes??""}/></F></>}
 {kind==="prayer"&&<><div className="grid gap-4 sm:grid-cols-2"><F label="Name"><input name="name" className={field} defaultValue={pr?.name??""}/></F><F label="Email"><input name="email" type="email" className={field} defaultValue={pr?.email??""}/></F><F label="Phone"><input name="phone" className={field} defaultValue={pr?.phone??""}/></F><F label="Category"><input name="category" className={field} defaultValue={pr?.category??"General"}/></F><F label="Urgency"><select name="urgency" className={field} defaultValue={pr?.urgency??"MEDIUM"}>{["LOW","MEDIUM","HIGH"].map(x=><option key={x}>{x}</option>)}</select></F></div><F label="Request"><textarea name="requestText" required rows={5} className={field} defaultValue={pr?.requestText}/></F><label className="flex gap-2 text-sm"><input type="checkbox" name="isAnonymous" defaultChecked={pr?.isAnonymous}/>Anonymous</label></>}
 {kind==="followUp"&&<><F label="Type"><select name="type" className={field}>{["PHONE_CALL","EMAIL","MESSAGE","PASTORAL_VISIT","OTHER"].map(x=><option key={x}>{x}</option>)}</select></F><F label="Due date"><input name="dueDate" type="datetime-local" className={field}/></F><F label="Notes"><textarea name="notes" required rows={4} className={field}/></F></>}
 {kind==="meeting"&&<><F label="Title"><input name="title" required className={field}/></F><div className="grid gap-4 sm:grid-cols-2"><F label="Start"><input name="startTime" type="datetime-local" required className={field}/></F><F label="End"><input name="endTime" type="datetime-local" className={field}/></F><F label="Location"><input name="location" className={field}/></F></div><F label="Description"><textarea name="description" rows={4} className={field}/></F></>}
 {kind==="member"&&<div className="grid gap-4 sm:grid-cols-2"><F label="Membership number"><input name="membershipNumber" className={field} defaultValue={m?.membershipNumber??""}/></F><F label="Join date"><input name="joinDate" type="datetime-local" className={field} defaultValue={local(m?.joinDate)}/></F><F label="Role"><input name="role" className={field} defaultValue={m?.role??"Member"}/></F><F label="Status"><select name="status" className={field} defaultValue={m?.status??"ACTIVE"}>{["NEW","ACTIVE","INACTIVE"].map(x=><option key={x}>{x}</option>)}</select></F></div>}
 {error&&<div className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}<div className="flex justify-end gap-3 border-t border-[#e8eef6] pt-5"><button type="button" onClick={onClose} className="rounded-xl bg-[#f0f4f9] px-5 py-2.5 font-bold text-[#6b7897]">Cancel</button><button disabled={saving} className="flex items-center gap-2 rounded-xl bg-[#0E5AA7] px-5 py-2.5 font-bold text-white">{saving&&<Loader2 size={15} className="animate-spin"/>}Save</button></div></div></form></div>
}
