import { useEffect, useState, type ReactNode } from "react";
import { Clock, Loader2, Plus, Save, Trash2 } from "lucide-react";
import { createServiceTime, deleteServiceTime, getChurchSettings, getServiceTimes, updateChurchSettings, updateServiceTime } from "@/lib/data";
import type { ChurchSettings, ServiceTime } from "@/types";
const input="w-full rounded-xl bg-[#f0f4f9] px-4 py-3 text-sm text-[#0d1b2e] outline-none focus:ring-2 focus:ring-[#0E5AA7]/20";
function Section({title,children}:{title:string;children:ReactNode}){return <section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="mb-5 border-b border-[#e8eef6] pb-3 font-black text-[#0d1b2e]">{title}</h2>{children}</section>}
function Field({label,value,onChange,multiline=false}:{label:string;value:string;onChange:(v:string)=>void;multiline?:boolean}){return <label className="block"><span className="mb-1.5 block text-xs font-black uppercase tracking-wide text-[#0d1b2e]">{label}</span>{multiline?<textarea rows={3} className={input} value={value} onChange={e=>onChange(e.target.value)}/>:<input className={input} value={value} onChange={e=>onChange(e.target.value)}/>}</label>}
type EditableService=Pick<ServiceTime,"id"|"dayOfWeek"|"label"|"time"|"location"|"sortOrder"|"isActive">;
export default function About(){
 const[settings,setSettings]=useState<ChurchSettings|null>(null),[services,setServices]=useState<EditableService[]>([]),[originalIds,setOriginalIds]=useState<string[]>([]),[busy,setBusy]=useState(true),[saved,setSaved]=useState(false),[error,setError]=useState("");
 useEffect(()=>{void(async()=>{try{const[s,t]=await Promise.all([getChurchSettings(),getServiceTimes()]);setSettings(s);setServices(t);setOriginalIds(t.map(i=>i.id))}catch(e){setError(e instanceof Error?e.message:"Unable to load settings.")}finally{setBusy(false)}})()},[]);
 const patch=(key:keyof ChurchSettings,value:unknown)=>setSettings(current=>current?{...current,[key]:value}:current);
 const save=async()=>{if(!settings)return;setBusy(true);setError("");try{await updateChurchSettings(settings.id,{churchName:settings.churchName,tagline:settings.tagline,bio:settings.bio,vision:settings.vision,mission:settings.mission,foundedYear:settings.foundedYear,seniorPastor:settings.seniorPastor,associatePastor:settings.associatePastor,address:settings.address,phone:settings.phone,email:settings.email,website:settings.website,socialLinks:settings.socialLinks});const deleted=originalIds.filter(id=>!services.some(s=>s.id===id));await Promise.all(deleted.map(deleteServiceTime));const persisted=await Promise.all(services.map((s,index)=>originalIds.includes(s.id)?updateServiceTime(s.id,{...s,sortOrder:index}):createServiceTime({...s,sortOrder:index})));setServices(persisted);setOriginalIds(persisted.map(i=>i.id));setSaved(true);setTimeout(()=>setSaved(false),2500)}catch(e){setError(e instanceof Error?e.message:"Unable to save settings.")}finally{setBusy(false)}};
 if(busy&&!settings)return <div className="flex justify-center p-20"><Loader2 className="animate-spin text-[#0E5AA7]"/></div>; if(!settings)return <div className="p-7 text-red-700">{error||"Church settings are unavailable."}</div>;
 return <div className="space-y-5 p-5 lg:p-7"><div className="flex items-start justify-between"><div><h1 className="text-2xl font-black text-[#0d1b2e]">About & Settings</h1><p className="mt-1 text-sm text-[#6b7897]">Manage information displayed on the public site</p></div><button disabled={busy} onClick={()=>void save()} className={`flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-bold text-white ${saved?"bg-green-600":"bg-[#0E5AA7]"}`}>{busy?<Loader2 size={16} className="animate-spin"/>:<Save size={16}/>} {saved?"Saved!":"Save Changes"}</button></div>{error&&<div className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}
 <Section title="Church Information"><div className="grid gap-4 md:grid-cols-2"><div className="md:col-span-2"><Field label="Church Name" value={settings.churchName} onChange={v=>patch("churchName",v)}/></div><div className="md:col-span-2"><Field label="Tagline" value={settings.tagline??""} onChange={v=>patch("tagline",v)}/></div><Field label="Founded Year" value={String(settings.foundedYear??"")} onChange={v=>patch("foundedYear",v?Number(v):null)}/><Field label="Senior Pastor" value={settings.seniorPastor??""} onChange={v=>patch("seniorPastor",v)}/><Field label="Associate Pastor" value={settings.associatePastor??""} onChange={v=>patch("associatePastor",v)}/></div></Section>
 <Section title="Vision, Mission & Story"><div className="space-y-4"><Field label="Vision" value={settings.vision??""} onChange={v=>patch("vision",v)} multiline/><Field label="Mission" value={settings.mission??""} onChange={v=>patch("mission",v)} multiline/><Field label="About / Bio" value={settings.bio??""} onChange={v=>patch("bio",v)} multiline/></div></Section>
 <Section title="Contact & Social Links"><div className="grid gap-4 md:grid-cols-2"><div className="md:col-span-2"><Field label="Address" value={settings.address??""} onChange={v=>patch("address",v)}/></div><Field label="Phone" value={settings.phone??""} onChange={v=>patch("phone",v)}/><Field label="Email" value={settings.email??""} onChange={v=>patch("email",v)}/><Field label="Website" value={settings.website??""} onChange={v=>patch("website",v)}/>{(["facebook","instagram","youtube","twitter"] as const).map(name=><Field key={name} label={name} value={settings.socialLinks[name]??""} onChange={v=>patch("socialLinks",{...settings.socialLinks,[name]:v||null})}/>)}</div></Section>
 <Section title="Service Times"><div className="mb-4 space-y-3">{services.map(s=><div key={s.id} className="flex flex-wrap items-center gap-3"><Clock size={15} className="text-[#0E5AA7]"/><select className={input+" w-auto"} value={s.dayOfWeek} onChange={e=>setServices(list=>list.map(i=>i.id===s.id?{...i,dayOfWeek:e.target.value}:i))}>{["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"].map(d=><option key={d}>{d}</option>)}</select><input className={input+" min-w-40 flex-1"} value={s.label} onChange={e=>setServices(list=>list.map(i=>i.id===s.id?{...i,label:e.target.value}:i))}/><input type="time" className={input+" w-32"} value={s.time.slice(0,5)} onChange={e=>setServices(list=>list.map(i=>i.id===s.id?{...i,time:e.target.value}:i))}/><button onClick={()=>setServices(list=>list.filter(i=>i.id!==s.id))} className="rounded-lg p-2 text-[#D7261E] hover:bg-red-50"><Trash2 size={14}/></button></div>)}</div><button onClick={()=>setServices(list=>[...list,{id:`new-${Date.now()}`,dayOfWeek:"Sunday",label:"Service",time:"10:00",location:null,sortOrder:list.length,isActive:true}])} className="flex items-center gap-2 rounded-xl bg-[#0E5AA7]/10 px-4 py-2.5 text-sm font-bold text-[#0E5AA7]"><Plus size={15}/>Add Service Time</button></Section></div>
}
