import { useEffect, useMemo, useState } from "react";
import { Clock, Edit2, Loader2, MapPin, Plus, Search, Trash2, Users } from "lucide-react";
import { AdminCmsDialog } from "@/app/components/admin/AdminCmsDialog";
import { AdminConfirmDialog } from "@/app/components/admin/AdminConfirmDialog";
import { createEvent, deleteEvent, getEvents, updateEvent, type EventInput } from "@/lib/data";
import type { Event } from "@/types";

const date = (value: string) => new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short", timeZone: "America/Jamaica" }).format(new Date(value));
export default function Events() {
  const [items,setItems]=useState<Event[]>([]),[search,setSearch]=useState(""),[status,setStatus]=useState("ALL"),[editing,setEditing]=useState<Event|null|undefined>(),[deleting,setDeleting]=useState<Event|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState("");
  useEffect(()=>{void (async()=>{try{setItems(await getEvents())}catch(e){setError(e instanceof Error?e.message:"Unable to load events.")}finally{setBusy(false)}})()},[]);
  const filtered=useMemo(()=>items.filter(i=>(status==="ALL"||i.status===status)&&`${i.title} ${i.eventType}`.toLowerCase().includes(search.toLowerCase())),[items,search,status]);
  const save=async(input:EventInput)=>{const saved=editing?await updateEvent(editing.id,input):await createEvent(input);setItems(list=>editing?list.map(i=>i.id===saved.id?saved:i):[saved,...list])};
  const remove=async()=>{if(!deleting)return;setBusy(true);try{await deleteEvent(deleting.id);setItems(list=>list.filter(i=>i.id!==deleting.id));setDeleting(null)}catch(e){setError(e instanceof Error?e.message:"Unable to delete event.")}finally{setBusy(false)}};
  return <div className="p-5 lg:p-7"><div className="mb-6 flex items-start justify-between"><div><h1 className="text-2xl font-black text-[#0d1b2e]">Events</h1><p className="mt-1 text-sm text-[#6b7897]">{items.filter(i=>i.status==="UPCOMING").length} upcoming · {items.filter(i=>i.status==="PAST").length} past</p></div><button onClick={()=>setEditing(null)} className="flex items-center gap-2 rounded-xl bg-[#0E5AA7] px-4 py-2.5 text-sm font-bold text-white"><Plus size={16}/>Create Event</button></div>
  <div className="mb-5 flex flex-wrap gap-3"><div className="relative min-w-52 flex-1"><Search size={14} className="absolute left-3 top-3 text-[#6b7897]"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search events..." className="w-full rounded-xl border border-[#e8eef6] bg-white py-2.5 pl-9 pr-4 text-sm outline-none"/></div>{["ALL","UPCOMING","PAST","CANCELLED"].map(s=><button key={s} onClick={()=>setStatus(s)} className={`rounded-xl px-3 py-2 text-xs font-semibold ${status===s?"bg-[#0E5AA7] text-white":"bg-white text-[#6b7897]"}`}>{s}</button>)}</div>
  {error&&<div className="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}{busy&&items.length===0?<div className="flex justify-center p-16"><Loader2 className="animate-spin text-[#0E5AA7]"/></div>:<div className="space-y-3">{filtered.map(item=><div key={item.id} className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div><div className="mb-2 flex flex-wrap items-center gap-2"><h3 className="font-black text-[#0d1b2e]">{item.title}</h3><span className="rounded-full bg-[#0E5AA7]/10 px-2 py-1 text-[10px] font-bold text-[#0E5AA7]">{item.status}</span><span className="rounded-full bg-green-50 px-2 py-1 text-[10px] font-bold text-green-700">{item.publicationStatus}</span></div><p className="mb-3 text-xs leading-relaxed text-[#6b7897]">{item.description}</p><div className="flex flex-wrap gap-4 text-xs text-[#6b7897]"><span className="flex gap-1.5"><Clock size={12}/>{date(item.startDate)}</span><span className="flex gap-1.5"><MapPin size={12}/>{item.location}</span><span className="flex gap-1.5"><Users size={12}/>{item.organizerName}</span></div></div><div className="flex shrink-0 gap-1"><button onClick={()=>setEditing(item)} className="rounded-lg p-2 text-[#6b7897] hover:bg-[#f0f4f9]"><Edit2 size={14}/></button><button onClick={()=>setDeleting(item)} className="rounded-lg p-2 text-[#6b7897] hover:bg-red-50 hover:text-[#D7261E]"><Trash2 size={14}/></button></div></div></div>)}</div>}
  {editing!==undefined&&<AdminCmsDialog kind="event" value={editing} onClose={()=>setEditing(undefined)} onSave={save}/>} {deleting&&<AdminConfirmDialog title="Delete event?" message={`This permanently removes "${deleting.title}".`} busy={busy} onCancel={()=>setDeleting(null)} onConfirm={()=>void remove()}/>}</div>
}
