import { useEffect, useState } from "react";
import { Download, Edit2, Loader2, Plus, Trash2 } from "lucide-react";
import { AdminCmsDialog } from "@/app/components/admin/AdminCmsDialog";
import { AdminConfirmDialog } from "@/app/components/admin/AdminConfirmDialog";
import { createGivingProgram, deleteGivingProgram, getGivingPrograms, getGivingTransactions, updateGivingProgram, type GivingProgramInput } from "@/lib/data";
import type { GivingProgram, GivingTransaction } from "@/types";
const money=(amount:number,currency:string)=>new Intl.NumberFormat("en-JM",{style:"currency",currency}).format(amount);
export default function Give(){
 const[programs,setPrograms]=useState<GivingProgram[]>([]),[transactions,setTransactions]=useState<GivingTransaction[]>([]),[editing,setEditing]=useState<GivingProgram|null|undefined>(),[deleting,setDeleting]=useState<GivingProgram|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState("");
 useEffect(()=>{void(async()=>{try{const[p,t]=await Promise.all([getGivingPrograms(),getGivingTransactions()]);setPrograms(p);setTransactions(t)}catch(e){setError(e instanceof Error?e.message:"Unable to load giving data.")}finally{setBusy(false)}})()},[]);
 const save=async(input:GivingProgramInput)=>{const saved=editing?await updateGivingProgram(editing.id,input):await createGivingProgram(input);setPrograms(list=>editing?list.map(i=>i.id===saved.id?saved:i):[saved,...list])};
 const remove=async()=>{if(!deleting)return;setBusy(true);try{await deleteGivingProgram(deleting.id);setPrograms(list=>list.filter(i=>i.id!==deleting.id));setDeleting(null)}catch(e){setError(e instanceof Error?e.message:"Unable to delete program.")}finally{setBusy(false)}};
 const exportCsv=()=>{const rows=[["Giver","Type","Amount","Currency","Method","Received"],...transactions.map(t=>[t.isAnonymous?"Anonymous":t.giverName??"",t.type,String(t.amount),t.currency,t.paymentMethod,t.receivedAt])];const blob=new Blob([rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n")],{type:"text/csv"});const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download="giving-transactions.csv";link.click();URL.revokeObjectURL(link.href)};
 return <div className="space-y-6 p-5 lg:p-7"><div className="flex items-start justify-between"><div><h1 className="text-2xl font-black text-[#0d1b2e]">Give Programs</h1><p className="mt-1 text-sm text-[#6b7897]">Track giving programs, goals, and transactions in Jamaican dollars</p></div><button onClick={()=>setEditing(null)} className="flex items-center gap-2 rounded-xl bg-[#0E5AA7] px-4 py-2.5 text-sm font-bold text-white"><Plus size={16}/>New Program</button></div>
 {error&&<div className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}{busy&&programs.length===0?<div className="flex justify-center p-16"><Loader2 className="animate-spin text-[#0E5AA7]"/></div>:<div className="grid gap-4 md:grid-cols-2">{programs.map(item=>{const progress=item.goalAmount?Math.round(item.amountRaised/item.goalAmount*100):0;return <div key={item.id} className="rounded-2xl bg-white p-5 shadow-sm"><div className="mb-4 flex items-start justify-between"><div><h3 className="font-black text-[#0d1b2e]">{item.name}</h3><p className="mt-1 text-xs text-[#6b7897]">{item.description}</p></div><div className="flex gap-1"><button onClick={()=>setEditing(item)} className="rounded-lg p-2 text-[#6b7897] hover:bg-[#f0f4f9]"><Edit2 size={14}/></button><button onClick={()=>setDeleting(item)} className="rounded-lg p-2 text-[#D7261E] hover:bg-red-50"><Trash2 size={14}/></button></div></div><div className="mb-2 flex items-end justify-between"><div><div className="text-xl font-black" style={{color:item.color??"#0E5AA7"}}>{money(item.amountRaised,item.currency)}</div><div className="text-xs text-[#6b7897]">of {item.goalAmount?money(item.goalAmount,item.currency):"open goal"}</div></div><div className="text-2xl font-black text-[#0d1b2e]">{progress}%</div></div><div className="h-2.5 overflow-hidden rounded-full bg-[#e8eef6]"><div className="h-full rounded-full" style={{width:`${Math.min(progress,100)}%`,backgroundColor:item.color??"#0E5AA7"}}/></div></div>})}</div>}
 <div><div className="mb-4 flex items-center justify-between"><h2 className="font-black text-[#0d1b2e]">Recent Transactions</h2><button onClick={exportCsv} disabled={!transactions.length} className="flex items-center gap-1.5 text-xs font-bold text-[#0E5AA7] disabled:opacity-40"><Download size={13}/>Export CSV</button></div><div className="overflow-hidden rounded-2xl bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full"><thead><tr className="border-b border-[#e8eef6] text-left text-[10px] uppercase tracking-widest text-[#6b7897]"><th className="px-5 py-4">Giver</th><th className="px-4 py-4">Type</th><th className="px-4 py-4">Method</th><th className="px-4 py-4">Received</th><th className="px-5 py-4 text-right">Amount</th></tr></thead><tbody className="divide-y divide-[#e8eef6]">{transactions.map(t=><tr key={t.id}><td className="px-5 py-4 text-sm font-semibold text-[#0d1b2e]">{t.isAnonymous?"Anonymous":t.giverName}</td><td className="px-4 py-4 text-xs text-[#6b7897]">{t.type}</td><td className="px-4 py-4 text-xs text-[#6b7897]">{t.paymentMethod}</td><td className="px-4 py-4 text-xs text-[#6b7897]">{new Date(t.receivedAt).toLocaleDateString()}</td><td className="px-5 py-4 text-right text-sm font-black text-green-700">{money(t.amount,t.currency)}</td></tr>)}</tbody></table></div>{!transactions.length&&<div className="p-8 text-center text-sm text-[#6b7897]">No transactions recorded yet.</div>}</div></div>
 {editing!==undefined&&<AdminCmsDialog kind="giving" value={editing} onClose={()=>setEditing(undefined)} onSave={save}/>} {deleting&&<AdminConfirmDialog title="Delete giving program?" message={`Transactions remain preserved, but "${deleting.name}" will be removed.`} busy={busy} onCancel={()=>setDeleting(null)} onConfirm={()=>void remove()}/>}</div>
}
