import { useEffect, useState } from "react";
import { Calendar, Edit2, Loader2, Mail, Plus, Trash2, Users } from "lucide-react";
import { AdminCmsDialog } from "@/app/components/admin/AdminCmsDialog";
import { AdminConfirmDialog } from "@/app/components/admin/AdminConfirmDialog";
import { createMinistry, deleteMinistry, getMinistries, updateMinistry, type MinistryInput } from "@/lib/data";
import type { Ministry } from "@/types";
export default function Ministries(){
 const[items,setItems]=useState<Ministry[]>([]),[editing,setEditing]=useState<Ministry|null|undefined>(),[deleting,setDeleting]=useState<Ministry|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState("");
 useEffect(()=>{void(async()=>{try{setItems(await getMinistries())}catch(e){setError(e instanceof Error?e.message:"Unable to load ministries.")}finally{setBusy(false)}})()},[]);
 const save=async(input:MinistryInput)=>{const saved=editing?await updateMinistry(editing.id,input):await createMinistry(input);setItems(list=>editing?list.map(i=>i.id===saved.id?saved:i):[...list,saved])};
 const remove=async()=>{if(!deleting)return;setBusy(true);try{await deleteMinistry(deleting.id);setItems(list=>list.filter(i=>i.id!==deleting.id));setDeleting(null)}catch(e){setError(e instanceof Error?e.message:"Unable to delete ministry.")}finally{setBusy(false)}};
 return <div className="p-5 lg:p-7"><div className="mb-6 flex items-start justify-between"><div><h1 className="text-2xl font-black text-[#0d1b2e]">Ministries</h1><p className="mt-1 text-sm text-[#6b7897]">{items.filter(i=>i.status==="ACTIVE").length} active ministries · {items.reduce((a,i)=>a+i.memberCount,0)} participants</p></div><button onClick={()=>setEditing(null)} className="flex items-center gap-2 rounded-xl bg-[#0E5AA7] px-4 py-2.5 text-sm font-bold text-white"><Plus size={16}/>New Ministry</button></div>
 {error&&<div className="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}{busy&&items.length===0?<div className="flex justify-center p-16"><Loader2 className="animate-spin text-[#0E5AA7]"/></div>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map(item=><div key={item.id} className="rounded-2xl bg-white p-5 shadow-sm"><div className="mb-4 flex justify-between gap-3"><div><h3 className="font-black text-[#0d1b2e]">{item.name}</h3><p className="mt-1 line-clamp-2 text-xs text-[#6b7897]">{item.description}</p></div><span className="h-fit rounded-full bg-green-50 px-2 py-1 text-[10px] font-bold text-green-700">{item.status}</span></div><div className="mb-4 grid grid-cols-2 gap-2"><div className="rounded-xl bg-[#f0f4f9] p-3 text-center"><div className="text-xl font-black text-[#0E5AA7]">{item.memberCount}</div><div className="text-[10px] text-[#6b7897]">Members</div></div><div className="rounded-xl bg-[#f0f4f9] p-3 text-center"><div className="text-xl font-black text-[#0d1b2e]">{item.volunteerCount}</div><div className="text-[10px] text-[#6b7897]">Volunteers</div></div></div><div className="mb-4 space-y-2 text-xs text-[#6b7897]"><div className="flex gap-2"><Users size={13}/>{item.leaderName??"Leadership team"}</div><div className="flex gap-2"><Calendar size={13}/>{item.meetingSchedule??"No schedule set"}</div></div><div className="flex gap-2 border-t border-[#e8eef6] pt-3"><button onClick={()=>setEditing(item)} className="flex flex-1 items-center justify-center gap-1 rounded-xl bg-[#0E5AA7]/10 py-2 text-xs font-bold text-[#0E5AA7]"><Edit2 size={13}/>Edit</button>{item.contactEmail&&<a href={`mailto:${item.contactEmail}`} className="rounded-xl bg-[#f0f4f9] p-2 text-[#6b7897]"><Mail size={14}/></a>}<button onClick={()=>setDeleting(item)} className="rounded-xl bg-red-50 p-2 text-[#D7261E]"><Trash2 size={14}/></button></div></div>)}</div>}
 {editing!==undefined&&<AdminCmsDialog kind="ministry" value={editing} onClose={()=>setEditing(undefined)} onSave={save}/>} {deleting&&<AdminConfirmDialog title="Delete ministry?" message={`This permanently removes "${deleting.name}".`} busy={busy} onCancel={()=>setDeleting(null)} onConfirm={()=>void remove()}/>}</div>
}
